#!/usr/bin/php
<?php
require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;

date_default_timezone_set('Europe/Madrid');

// CLI
$app = new Application();
$app->add(new Trackr\Command\Stats('stats'));
$app->add(new Trackr\Command\Thresholds('thresholds'));
$app->add(new Trackr\Command\Tick('tick'));
$app->add(new Trackr\Command\Timetable('timetable'));
$app->run();